openapi: 3.0.0
info:
  title: Social Hub App
  description: Not my first social app - Max
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of the app
  - url: https://localhost:4000/api/v1
    description: mock url

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer